let bookJson = [
	{
	"title": "Annihilation of Caste",
	"author": "B.R. Ambedkar",
	"description": "A groundbreaking critique of the caste system in India, originally written as a speech, highlighting the need for social reform and equality.",
	"category": "Non-Fiction, Social Reform",
	"publisher": "Navayana Publishing",
	"language": "English",
	"pages": 200,
	"quantity" : 10,
	"isAvailable" : true,
	"newPrice": 299,
	"oldPrice": 350,
	"coverPic": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1613727572i/8521879.jpg"
  },
  {
	"title": "The Great Gatsby",
	"author": "F. Scott Fitzgerald",
	"description": "A classic novel of the Roaring Twenties, exploring themes of wealth, love, and the American Dream.",
	"category": "Fiction",
	"publisher": "Scribner",
	"language": "Hindi",
	"pages": 180,
	"quantity" : 10,
	"isAvailable" : true,
	"newPrice": 299,
	"oldPrice": 399,
	"coverPic": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbwf8sNSJn4CjQhWqnZaIo-6GNHjxwb8KUpg&s"
  },
  {
	"title": "Sapiens: A Brief History of Humankind",
	"author": "Yuval Noah Harari",
	"description": "A fascinating exploration of the history of humankind from the Stone Age to the modern day.",
	"category": "History",
	"publisher": "Harper",
	"language": "English,French",
	"pages": 498,
	"quantity" : 10,
	"isAvailable" : true,
	"newPrice": 499,
	"oldPrice": 599,
	"coverPic": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0FxCfM-_t-RbeO2sctksNPeHO2cPndNQPLg&s"
  },
  {
	"title": "The Subtle Art of Not Giving a F*ck",
	"author": "Mark Manson",
	"description": "A counterintuitive approach to living a good life by embracing challenges and setting realistic expectations.",
	"category": "Self-Help",
	"publisher": "HarperOne",
	"language": "English",
	"pages": 224,
	"quantity" : 10,
	"isAvailable" : true,
	"newPrice": 399,
	"oldPrice": 499,
	"coverPic": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Sq6qyg3JCZ7uMau_WNJ-nwo2TRVEhpI_FA&s"
  },
  {
	"title": "The Lean Startup",
	"author": "Eric Ries",
	"description": "A practical guide to creating successful startups by focusing on rapid prototyping and customer feedback.",
	"category": "Business",
	"publisher": "Crown Business",
	"language": "English",
	"pages": 336,
	"quantity" : 10,
	"isAvailable" : true,
	"newPrice": 449,
	"oldPrice": 599,
	"coverPic": "https://images-eu.ssl-images-amazon.com/images/I/81vvgZqCskL._AC_UL210_SR210,210_.jpg"
  },
  {
	"title": "To Kill a Mockingbird",
	"author": "Harper Lee",
	"description": "A powerful tale of racial injustice and moral growth in the Deep South.",
	"category": "Classic Literature",
	"publisher": "J.B. Lippincott & Co.",
	"language": "English",
	"pages": 281,
	"quantity" : 10,
	"isAvailable" : true,
	"newPrice": 349,
	"oldPrice": 450,
	"coverPic": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReVo4KYmcwAMzNQy2_Larrs0NfPGXuHEwkVQ&s"
  },
  {
	"title": "Brief Answers to the Big Questions",
	"author": "Stephen Hawking",
	"description": "The final thoughts of Stephen Hawking on the biggest questions of our time, including space exploration and the existence of God.",
	"category": "Science",
	"publisher": "Bantam",
	"language": "English",
	"pages": 256,
	"quantity" : 10,
	"isAvailable" : true,
	"newPrice": 499,
	"oldPrice": 599,
	"coverPic": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn0YO4Hc96mZH3LcO5Slo-5PWoIdPjXi_crg&s"
  },
  {
	"title": "The Alchemist",
	"author": "Paulo Coelho",
	"description": "A spiritual journey of a shepherd boy who dreams of finding treasure in the pyramids of Egypt.",
	"category": "Philosophy",
	"publisher": "HarperOne",
	"language": "English",
	"pages": 208,
	"quantity" : 10,
	"isAvailable" : true,
	"newPrice": 299,
	"oldPrice": 399,
	"coverPic": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTo5BjecKebaDja26psMXjL9hNIW8r173FwCg&s"
  },
  {
	"title": "Atomic Habits",
	"author": "James Clear",
	"description": "An insightful book on how small changes in habits can lead to remarkable results in life.",
	"category": "Productivity",
	"publisher": "Avery",
	"language": "English, Hindi",
	"pages": 320,
	"quantity" : 10,
	"isAvailable" : true,
	"newPrice": 499,
	"oldPrice": 650,
	"coverPic": "https://images.squarespace-cdn.com/content/v1/59c82ac46f4ca30b86d179bf/1706362642426-BI3J8PJ5LRJNO8H7WFV4/119.bookreview.AtomicHabits.jpg"
  },
  {
	"title": "The 3 Mistakes of My Life",
	"author": "Chetan Bhagat",
	"description": "This book is a story about three friends navigating their lives in the backdrop of cricket, religion, and business in modern India",
	"category": "Fiction",
	"publisher": "Rupa Publications",
	"language": "English",
	"pages": 200,
	"quantity" : 10,
	"isAvailable" : true,
	"newPrice": 150,
	"oldPrice": 200,
	"coverPic": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1216107646i/3320520.jpg"
  }]